### ISSUE TITLE
enhancement mqtt add loop completed mqtt topic

### ISSUE THREAD

**Issue by riker65** [TheWandrr/vedirect_to_mqtt#4]
Hi

am not not good enough in c

where can I place a fix mqtt publish to identify the 
reading loop is completed .

just a fix payload and topic.

need this to join all together for a json string to be put into influxdb via nodered

Thanks for a hint

BR T

**Comment by TheWandrr** [comment]
The bridging code doesn't really have a defined "loop", as it asynchronously processes whatever it sees on the serial bus.  It translates each of these to an MQTT message as it is received.

I don't know how the database is set up that you're trying to populate, but when I've done similar it has involved a DB row for each message, rather than what I think you're trying to do - which is to consolidate all of the messages for a given "sample" into one row.

**Comment by riker65** [comment]
> The bridging code doesn't really have a defined "loop", as it asynchronously processes whatever it sees on the serial bus. It translates each of these to an MQTT message as it is received.
> 
> I don't know how the database is set up that you're trying to populate, but when I've done similar it has involved a DB row for each message, rather than what I think you're trying to do - which is to consolidate all of the messages for a given "sample" into one row.

Hi 

thanks yes I tried to consolidating into one row . Node Red works best if a msg completed topic / flag is available.

Thanks for looking into this

T
